# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.hicpotts_iterated_eb_priors_cpp <- function(y, cov1, cov2, cov3, cov4, z) {
    .Call(`_HiCPotts_hicpotts_iterated_eb_priors_cpp`, y, cov1, cov2, cov3,
        cov4, z)
}

.hicpotts_soft_eb_priors_cpp <- function(y, cov1, cov2, cov3, cov4, weight1,
    weight2, weight3) {
    .Call(`_HiCPotts_hicpotts_soft_eb_priors_cpp`, y, cov1, cov2, cov3,
        cov4, weight1, weight2, weight3)
}

.hicpotts_cached_posterior_cpp <- function(beta, z, y, component, theta,
    size_value, dist, cov1, cov2, cov3, cov4, priors) {
    .Call(`_HiCPotts_hicpotts_cached_posterior_cpp`, beta, z, y, component,
        theta, size_value, dist, cov1, cov2, cov3, cov4, priors)
}

.hicpotts_noise_relationship_logprior_cpp <- function(beta1, beta2, beta3,
    covariate_sds, link_sd = 0.5, order_strength = 10, order_width = 0.5) {
    .Call(`_HiCPotts_hicpotts_noise_relationship_logprior_cpp`, beta1,
        beta2, beta3, covariate_sds, link_sd, order_strength, order_width)
}

.hicpotts_branch_prior_logratio_cpp <- function(beta1, beta2, beta3,
    covariate_sds, link_sd = 0.5, order_strength = 10, order_width = 0.5) {
    .Call(`_HiCPotts_hicpotts_branch_prior_logratio_cpp`, beta1, beta2,
        beta3, covariate_sds, link_sd, order_strength, order_width)
}

.hicpotts_gamma_proposal_logratio_cpp <- function(current, proposed,
    local_step = 0.5, large_probability = 0.1, large_multiplier = 4,
    independence_probability = 0.05, prior_shape1 = 1, prior_shape2 = 1) {
    .Call(`_HiCPotts_hicpotts_gamma_proposal_logratio_cpp`, current,
        proposed, local_step, large_probability, large_multiplier,
        independence_probability, prior_shape1, prior_shape2)
}

.hicpotts_cluster_transition_counts <- function(z, y, cov1, cov2, cov3,
    cov4, beta, sizes, gamma, dist, repetitions = 10000L) {
    .Call(`_HiCPotts_hicpotts_cluster_transition_counts`, z, y, cov1, cov2,
        cov3, cov4, beta, sizes, gamma, dist, repetitions)
}

.hicpotts_cell_logweights_cpp <- function(z, y, betas, sizes, theta, gamma,
    dist, cov1, cov2, cov3, cov4, row, column) {
    .Call(`_HiCPotts_hicpotts_cell_logweights_cpp`, z, y, betas, sizes,
        theta, gamma, dist, cov1, cov2, cov3, cov4, row, column)
}

.hicpotts_theta_loglik <- function(z_current, y, b1, cov1, cov2, cov3, cov4,
    size1, theta_eval, dist) {
    .Call(`_HiCPotts_hicpotts_theta_loglik`, z_current, y, b1, cov1, cov2,
        cov3, cov4, size1, theta_eval, dist)
}

.hicpotts_theta_gibbs_step_cpp <- function(z_current, y, b1, cov1, cov2,
    cov3, cov4, size1, theta_current, dist) {
    .Call(`_HiCPotts_hicpotts_theta_gibbs_step_cpp`, z_current, y, b1, cov1,
        cov2, cov3, cov4, size1, theta_current, dist)
}

.hicpotts_simulate_potts_labels_cpp <- function(N, gamma, sweeps = 500L) {
    .Call(`_HiCPotts_hicpotts_simulate_potts_labels_cpp`, N, gamma, sweeps)
}

.hicpotts_calibrate_abc_epsilon_cpp <- function(N,
    gamma_prior_shape1 = 1, gamma_prior_shape2 = 1,
    abc_epsilon_quantile = 0.1, abc_potts_sweeps_arg = 0L,
    abc_sim_reps = 4L, abc_calibration_reps = 60L) {
    .Call(`_HiCPotts_hicpotts_calibrate_abc_epsilon_cpp`,
        N, gamma_prior_shape1, gamma_prior_shape2,
        abc_epsilon_quantile, abc_potts_sweeps_arg,
        abc_sim_reps, abc_calibration_reps)
}

#' @title MCMC Chain Function for the HMRFHiC Model
#'
#' @description
#' The function integrates multiple steps, including proposal distributions,
#' acceptance/rejection steps based on posterior calculations,
#' and retained-state ABC updates for the \\eqn{\\gamma} parameter.
#' Covariates and prior specifications can be either
#' data-driven or user-defined. The output includes the chains of sampled
#' parameters across the specified number of iterations.
#'
#' @details
#' Gamma uses a retained-state ABC-MCMC transition on a
#' composition-corrected latent-label adjacency summary, a Gaussian kernel,
#' and a default 10-percent prior-predictive tolerance quantile.
#'
#'
#' @param N Integer specifying the dimension of the lattice (\\eqn{N \\times
#' N}).
#'
#' @param gamma_prior Numeric. The STARTING value for the interaction parameter
#'   \\eqn{\\gamma} in the Potts model. Note this sets only the initial state of
#'   the chain; the prior density used in the gamma acceptance ratio is the Beta
#'   distribution given by \\code{gamma_prior_shape1} and
#'   \\code{gamma_prior_shape2}.
#'
#' @param iterations Integer. The number of MCMC iterations to run.
#'
#' @param x_vars A list of covariates used as predictors in the model. This
#' list should contain named elements
#' corresponding to 'distance', 'GC', 'TES', and 'ACC', each containing a
#' list of matrices of values for all \\eqn{N \\times N}.
#'
#' @param y An \\eqn{N \\times N} numeric matrix of observed interaction
#' counts. Each element corresponds to interacting locus (i,j).
#'
#' @param use_data_priors Logical. If \\code{TRUE}, data-driven priors will
#' be used for each component.
#'   If \\code{FALSE}, then \\code{user_fixed_priors} must be provided.
#'
#' @param user_fixed_priors (Optional) A list of user-specified priors for
#' the model components if
#' \\code{use_data_priors = FALSE}. Each components priors should be
#' specified as a list of means and standard
#'   deviations for the parameters.
#'
#' @param dist A character string specifying the distribution family to use:
#'   \\itemize{
#'     \\item \\code{'Poisson'}: Poisson distribution
#'     \\item \\code{'NB'}: Negative Binomial distribution
#'     \\item \\code{'ZIP'}: Zero-Inflated Poisson distribution
#'     \\item \\code{'ZINB'}: Zero-Inflated Negative Binomial distribution
#'   }
#'   The default is \\code{'ZIP'}.
#'
#' @param epsilon Optional positive ABC bandwidth. If NULL, a deterministic
#'   prior-predictive pilot quantile is used. Supplying a value skips the pilot
#'   simulations entirely.
#'
#' @param distance_metric Retained for source compatibility and ignored.
#'
#' @param size_start (Optional) Required if \\code{dist} is 'NB' or 'ZINB'.
#' A numeric vector of length 3 specifying
#' initial values for the size (overdispersion) parameter for each of the 3
#' components.
#'
#' @param theta_start (Optional) A numeric value providing an initial value
#' for \\eqn{\\theta}, the zero-inflation
#' parameter in ZIP/ZINB models. If not provided and \\code{dist} is ZIP or
#' ZINB, \\eqn{\\theta} is initialized to 0.5.
#'
#' @param z_start Optional N-by-N starting allocation with labels 1, 2 and 3.
#' @param beta_start Optional 3-by-5 matrix of starting regression
#'   coefficients. This is primarily useful for known-truth validation.
#' @param validation_freeze_z,validation_freeze_beta,validation_freeze_gamma
#'   Simulation-diagnostic controls that hold the named state block at its
#'   supplied starting value. All default to false and therefore do not
#'   alter production inference. A frozen beta block requires
#'   \\code{beta_start}.
#' @param validation_freeze_size,validation_freeze_theta
#'   Simulation-diagnostic controls for the dispersion and zero-inflation
#'   blocks. Frozen dispersion requires \\code{size_start} and frozen theta
#'   requires \\code{theta_start} under the corresponding emission family.
#' @param mcse_stop Whether to stop when every monitored parameter satisfies
#'   the batch-means relative MCSE rule.
#' @param mcse_min_iterations Minimum updates before an MCSE check.
#' @param mcse_check_interval Updates between MCSE checks.
#' @param mcse_relative_threshold Maximum MCSE/posterior-SD ratio required
#'   for stopping before the user-requested iteration count.
#' @param tempering_warmup Optional cyclical heating updates for latent-state
#'   warm-up. Zero is the tested default; retained sampling uses temperature 1.
#' @param tempering_beta_min Lowest optional warm-up inverse temperature.
#' @param tempering_cycle Positive optional heating-cycle length.
#'
#' @param gamma_prior_shape1,gamma_prior_shape2 Positive shape parameters of the
#'   Beta prior on \\eqn{\\gamma} used in either gamma transition, and for the
#'   legacy ABC tolerance calibration. Default \\code{1, 1}, i.e.
#'   Beta(1,1) = Uniform(0, 1): a flat prior whose density is constant, so it
#'   contributes exactly zero to the acceptance ratio and pulls \\eqn{\\gamma}
#'   toward no particular value.
#'
#'   The previous behaviour was a hardcoded Beta(2,2), whose mean of 0.5 sits
#' above any realistic Potts coupling and biased \\eqn{\\gamma} upward
#' whenever
#'   the tolerance was loose.
#'
#'   In a screening study over nine simulated datasets at
#'   \\eqn{\\gamma \\in \\{0.15, 0.30, 0.45\\}}, the flat prior had the lowest
#'   worst-case absolute bias across \\eqn{\\gamma} at the default tolerance
#'   (0.032, against 0.045 for Beta(2,2) and 0.066 for Beta(1,3)), and was by
#'   far the most stable across tolerance choices: its worst-case bias ranged
#'   only 0.032-0.049 over quantiles 0.05-0.30, where Beta(2,2) degraded to
#'   0.155 and Beta(1,3) to 0.120. That stability means results depend far
#'   less on the tolerance setting. The cost is wider intervals (0.268 versus
#'   0.200 for Beta(1,3) at quantile 0.10), which is the honest price of not
#'   injecting prior information.
#'
#'   Informative alternatives remain available: Beta(1,3) (mean 0.25) if weak
#'   coupling is genuinely expected, or Beta(2,2) to reproduce results from
#'   versions before 1.3.7. Note the study covered \\eqn{\\gamma} only up to
#'   0.45 and used three datasets per cell, so per-cell estimates are noisy;
#'   it is a screening study, not simulation-based calibration.
#'
#' @param abc_epsilon_quantile Numeric in (0, 1). Quantile of the
#'   prior-predictive summary distances used as the ABC tolerance when
#'   \\code{epsilon} is not supplied. Default \\code{0.10}; the previous
#'   hardcoded value was \\code{0.30}, which produced a tolerance comparable to
#' the between-\\eqn{\\gamma} signal so that the prior dominated the
#' posterior.
#'   Smaller values sharpen the ABC approximation at the cost of a lower
#'   acceptance rate. Ignored when \\code{epsilon} is supplied.
#'
#' @param gamma_update_interval Positive integer. The selected gamma step - the
#'   dominant per-iteration cost - runs only every \\code{gamma_update_interval}
#'   iterations; on the others gamma is held fixed while beta/size/theta/z
#'   continue to update. Default \\code{5}. Setting it to
#'   \\code{k} divides the gamma cost by ~\\code{k} and thins the gamma chain by
#'   \\code{k}. Inspect retained gamma movement when choosing this interval.
#'   Per-iteration cost of the gamma step is
#'   approximately \\code{abc_sim_reps * abc_potts_sweeps * N^2}.
#'
#' @param abc_potts_sweeps_arg Integer. Number of Gibbs sweeps per simulated
#'   Potts field. \\code{0} (default) uses the N-dependent rule
#'   \\code{max(100, 100 * N^2 / 400)}. A positive value overrides it. The
#'   default is conservative for weak coupling (gamma well below the critical
#'   value ~1); reducing it speeds simulation but, if set too low, the
#'   simulated field is not stationary and the summary-vs-gamma relationship
#'   shifts, re-biasing gamma. Validate against the estimating equation before
#'   reducing.
#'
#' @param abc_sim_reps Positive integer; number of simulated fields averaged
#'   per ABC candidate.
#' @param z_probability_burnin_arg Integer iteration after which latent-state
#'   membership frequencies are accumulated for classification. The default
#'   \\code{-1} selects an automatic value. This controls returned summaries
#'   only and does not change an MCMC transition or target distribution.
#'
#' @param comp23_barrier_kappa Strength of the smooth crossing-barrier penalty
#'   that discourages the component 2 and 3 baseline intensities from sitting
#'   on top of one another (the mechanism behind label-switching flicker).
#'   The default is \\code{10}, so this separation term and the component-1/3
#'   biological relationship prior are both active.
#' @param comp23_barrier_w Width of that penalty, i.e. how close the two
#'   intercepts must be before it bites. The default \\code{0.3} reproduces the
#'   historical hardcoded value. Must be positive.
#' @param use_noise_relationship_prior Logical. If \\code{TRUE} (default),
#'   component 3 is coupled to approximately the component-1 slopes and softly
#'   preferred above component 1 in intercept. Component 2 is absent from this
#'   coupled term and remains the unrestricted true-signal component.
#' @param noise_link_sd Positive standard deviation controlling shrinkage of
#'   component-1 versus false-signal slope differences on the standardised
#'   log1p-covariate scale. Smaller values enforce closer slopes.
#' @param noise_order_strength Non-negative strength of the soft preference
#'   that false-signal noise has a higher intercept than component 1.
#' @param noise_order_width Positive transition width of that soft intercept
#'   preference on the log-mean scale.
#' @param branch_swap_interval Non-negative integer. When positive, attempt
#'   the reversible whole component-2/component-3 branch transition at this
#' interval. The default is every iteration; zero disables it. The move is
#' active only with the labelled
#'   component-1/3 relationship prior.
#' @param signal_block_move_interval Non-negative integer interval for the
#'   connected component-2/component-3 cluster move. Zero disables it.
#' @param gamma_large_jump_probability Conditional probability of using the
#'   wider logit-normal gamma proposal rather than the adaptive local proposal.
#' @param gamma_large_jump_multiplier Positive multiplier applied to the local
#'   logit proposal scale for a wide jump.
#' @param gamma_independence_probability Probability of proposing gamma
#'   independently from its configured Beta prior. The complete mixture
#'   density is used in the Metropolis-Hastings ratio.
#' @param gamma_method Retained for source compatibility. The only supported
#'   value is \\code{'abc'}; the exchange-style transition has been removed.
#' @param verbose Logical. Print periodic sampler progress when true. The
#'   default is false so parallel and batch execution remain quiet.
#' @param progress_interval Positive number of iterations between progress
#'   messages when \\code{verbose = TRUE}.
#'
#' @return
#' A \\code{list} containing:
#' \\itemize{
#' \\item \\code{chains}: A list of three \\eqn{(iterations+1) \\times 5}
#' matrices, each storing the parameter chains
#'         for one of the three components.
#' \\item \\code{gamma}: A numeric vector of length \\eqn{iterations+1}, the
#' chain of \\eqn{\\gamma} values.
#' \\item \\code{theta}: A numeric vector of length \\eqn{iterations+1}, the
#' chain of \\eqn{\\theta} values
#'         (or initialized and unchanged if not ZIP/ZINB).
#' \\item \\code{size}: A \\eqn{3 \\times (iterations+1)} matrix of size
#' (overdispersion) parameters
#' if \\code{dist} is NB or ZINB; otherwise, this matrix might be unused.
#'   \\item \\code{z_final}: Final unrestricted latent-state draw.
#'   \\item \\code{z_checkpoints}: Unrestricted latent-state snapshots retained
#'         for trajectory diagnostics.
#' \\item \\code{z_probabilities}: Three \\eqn{N \\times N} matrices
#' containing
#'         post-burn-in MCMC membership frequencies. These directly estimate
#'         the posterior probability of each component at every cell without
#'         changing the sampler or applying a mean-field approximation.
#' \\item \\code{z_probability_draws}: Number of latent-state draws
#' accumulated
#'         in \\code{z_probabilities}.
#'   \\item \\code{performance}: Cached-native engine flags plus total and
#'         stage-specific elapsed times.
#'   \\item \\code{sampler_settings}: Dimensions, distribution, completed
#'         iterations and computational settings needed to audit the fit.
#' }
#'
#' @examples
#'
#' N <- 10
#' gamma_prior <- 0.5
#' iterations <- 10
#' x_vars <- list(
#'   distance = list(matrix(runif(N*N, 0, 10), nrow=N)),
#'   GC = list(matrix(runif(N*N, 0, 1), nrow=N)),
#'   TES = list(matrix(runif(N*N, 0, 2), nrow=N)),
#'   ACC = list(matrix(runif(N*N, 0, 5), nrow=N))
#' )
#' y <- matrix(rpois(N*N, lambda=5), nrow=N)
#'
#' # Using data-driven priors, ZIP distribution, no user_fixed_priors:
#' results <- run_metropolis_MCMC_betas(
#'   N = N,
#'   gamma_prior = gamma_prior,
#'   iterations = iterations,
#'   x_vars = x_vars,
#'   y = y,
#'   use_data_priors = TRUE,
#'   dist = 'ZIP'
#' )
#'
#' # Inspect gamma chain:
#' plot(results$gamma, type='l')
#'
#' @aliases run_metropolis_MCMC_betas
#'
#' @noRd
run_metropolis_MCMC_betas <- function(N, gamma_prior,
    iterations, x_vars, y, use_data_priors, user_fixed_priors = NULL,
    dist = "ZIP", epsilon = NULL, distance_metric = "manhattan",
    size_start = NULL, theta_start = NULL, z_start = NULL,
    mcse_stop = TRUE, mcse_min_iterations = 10000L,
    mcse_check_interval = 500L, mcse_relative_threshold = 0.05,
    tempering_warmup = 0L, tempering_beta_min = 0.3,
    tempering_cycle = 500L, gamma_prior_shape1 = 1,
    gamma_prior_shape2 = 1, abc_epsilon_quantile = 0.1,
    gamma_update_interval = 5L, abc_potts_sweeps_arg = 0L,
    abc_sim_reps = 4L, z_probability_burnin_arg = -1L,
    comp23_barrier_kappa = 10, comp23_barrier_w = 0.3,
    use_noise_relationship_prior = TRUE, noise_link_sd = 0.5,
    noise_order_strength = 10, noise_order_width = 0.5,
    branch_swap_interval = 1L, signal_block_move_interval = 5L,
    gamma_large_jump_probability = 0.1, gamma_large_jump_multiplier = 4,
    gamma_independence_probability = 0.05, gamma_method = "abc",
    verbose = FALSE, progress_interval = 50L, beta_start = NULL,
    validation_freeze_z = FALSE, validation_freeze_beta = FALSE,
    validation_freeze_gamma = FALSE, validation_freeze_size = FALSE,
    validation_freeze_theta = FALSE) {
    .Call(`_HiCPotts_run_metropolis_MCMC_betas`, N,
        gamma_prior, iterations, x_vars, y, use_data_priors,
        user_fixed_priors, dist, epsilon, distance_metric,
        size_start, theta_start, z_start, mcse_stop,
        mcse_min_iterations, mcse_check_interval, mcse_relative_threshold,
        tempering_warmup, tempering_beta_min, tempering_cycle,
        gamma_prior_shape1, gamma_prior_shape2, abc_epsilon_quantile,
        gamma_update_interval, abc_potts_sweeps_arg,
        abc_sim_reps, z_probability_burnin_arg, comp23_barrier_kappa,
        comp23_barrier_w, use_noise_relationship_prior,
        noise_link_sd, noise_order_strength, noise_order_width,
        branch_swap_interval, signal_block_move_interval,
        gamma_large_jump_probability, gamma_large_jump_multiplier,
        gamma_independence_probability, gamma_method,
        verbose, progress_interval, beta_start, validation_freeze_z,
        validation_freeze_beta, validation_freeze_gamma,
        validation_freeze_size, validation_freeze_theta)
}

#' @name Neighbours_combined
#' @title Neighbours Function for the Potts Model
#'
#' @description
#' Computes the number of agreeing neighbors for each site in a Potts model
#' lattice.
#' The Potts model is a generalization of the Ising model, where each site
#' on a lattice can
#' take on multiple states. By counting how many of a site's four neighbors
#' share the same
#' state, this function provides a measure of clustering within the lattice.
#'
#' @usage
#' Neighbours_combined(potts_data, N, proposed_value = NULL)
#'
#' @param potts_data A numeric \\eqn{N \\times N} matrix representing the
#' current configuration
#' of the Potts model. Each element corresponds to the state of a particular
#' site.
#'
#' @param N An integer specifying the dimension of the \\code{potts_data}
#' lattice (i.e., the
#'   lattice has \\code{N} rows and \\code{N} columns).
#'
#' @param proposed_value (Optional) A numeric \\eqn{N \\times N} matrix
#' representing a proposed
#' configuration of the Potts model. If provided, the function computes
#' neighbor relationships
#' relative to this proposed configuration; otherwise, it uses a shifted
#' version of \\code{potts_data}
#'   to determine neighbors.
#'
#' @details
#' The function checks each site and compares it with its four directional
#' neighbors
#' (up, down, left, right). For each neighbor that has the same state, a
#' value of 1 is assigned.
#' Summing these values for each site results in a measure of how 'similar'
#' the immediate neighborhood
#' is to that site.
#'
#' Internally, the function:
#' \\enumerate{
#' \\item Uses \\code{shift_matrix} to create versions of the lattice
#' shifted in each of the four directions.
#' \\item Uses \\code{compute_neighbours} to determine if neighboring
#' positions match in state.
#' \\item Sums the contributions from all four directions to form the
#' \\code{Neighbours_total} matrix.
#' }
#'
#' By providing an optional \\code{proposed_value} matrix, this function can
#' be integrated into an
#' MCMC algorithm where new configurations are proposed and evaluated 
#' based on their local coherence.
#'
#' @return
#' A numeric \\eqn{N \\times N} matrix, \\code{Neighbours_total}, where each
#' element is the count of
#' how many of the four neighbors match the state of that site.
#'
#' @examples
#' 
#' # Suppose we have a 5x5 Potts model lattice:
#' potts_data <- matrix(sample(1:3, 25, replace = TRUE), ncol = 5)
#' N <- 5
#'
#' # Compute the neighbors without a proposed configuration:
#' neigh <- Neighbours_combined(potts_data, N)
#' neigh
#'
#' # Suppose we propose a new configuration:
#' proposed <- matrix(sample(1:3, 25, replace = TRUE), ncol = 5)
#'
#' # Evaluate neighbors for the proposed configuration:
#' neigh_proposed <- Neighbours_combined(
#'   potts_data, N,
#'   proposed_value = proposed
#' )
#' neigh_proposed
#' 
#' @noRd
#'
Neighbours_combined <- function(potts_data, N, proposed_value = NULL) {
    .Call(`_HiCPotts_Neighbours_combined`, potts_data, N, proposed_value)
}

#' @title Posterior Function for the Potts Model
#'
#' @description
#' This function computes the posterior of the Potts model combined with an
#' interaction count model
#' (e.g., from genomic interactions data), incorporating mixture components,
#' neighbor relationships,
#' and distributional assumptions (Poisson, Negative Binomial, Zero-Inflated
#' Poisson, Zero-Inflated Negative Binomial).
#' It returns the log-probabilities for each site on the lattice under the
#' specified model configuration.
#'
#' @usage
#' pz_123(z, sum_neighbours, y, pred_combined, chains, chain_gamma,
#'        x_vars, theta, size_chain, N, iter, dist)
#'
#' @param z A numeric \\eqn{N \\times N} matrix representing the component
#' assignments for each site on the lattice.
#' Each element is a component label (e.g., 1, 2, or 3), indicating which
#' mixture component that interaction currently belongs to.
#'
#' @param sum_neighbours An \\eqn{N \\times N} numeric matrix representing
#' the number of neighboring sites
#' (up, down, left, right) that agree in state with each site. Typically
#' computed by the function
#'   \\code{Neighbours_combined()}.
#'
#' @param y An \\eqn{N \\times N} numeric matrix of observed interaction
#' counts (e.g., genomic interaction data).
#'   Each element corresponds to the count observed at that site.
#'
#' @param pred_combined An R function (passed from R to C++) that computes
#' predicted values (linear predictors)
#' for the specified component. This is often a reference to the
#' \\code{pred_combined()} function in R.
#'
#' @param chains A \\code{list} of parameter vectors (MCMC chains) for the
#' model. Each element corresponds to
#'   a component and contains the parameters associated with that component.
#'
#' @param chain_gamma A numeric vector (using ABC algorithm) for the
#' interaction parameter \\eqn{\\gamma} that governs
#' neighbor effects in the Potts model. The \\code{iter}-th element of this
#' vector is used in the calculation.
#'
#' @param x_vars A list of covariates (sources of biases), each a nested
#' structure as used by
#' \\code{pred_combined()}. These covariates are used to compute
#' component-specific predicted values (\\eqn{\\lambda}).
#'
#' @param theta A numeric scalar representing the zero-inflation parameter.
#' Used when the distribution is
#' Zero-Inflated Poisson (ZIP) or Zero-Inflated Negative Binomial (ZINB),
#' typically for the first component.
#'
#' @param size_chain An \\eqn{3 \\times M} matrix representing the MCMC
#' draws of the size (overdispersion) parameter
#' for Negative Binomial or Zero-Inflated Negative Binomial distributions.
#' One row per component, and columns
#' correspond to iterations. The value at \\code{size_chain[comp - 1, iter]}
#' is used for the specified iteration.
#'
#' @param N An integer specifying the dimension of the lattice (\\eqn{N
#' \\times N}).
#'
#' @param iter An integer indicating which iteration of the MCMC chains
#' (parameters, \\eqn{\\gamma}, size) to use
#'   in the calculation.
#'
#' @param dist A character string specifying the distribution:
#'   \\itemize{
#'     \\item \\code{'Poisson'}: Poisson distribution
#'     \\item \\code{'NB'}: Negative Binomial distribution
#'     \\item \\code{'ZIP'}: Zero-Inflated Poisson distribution
#'     \\item \\code{'ZINB'}: Zero-Inflated Negative Binomial distribution
#'   }
#'
#' @details
#' This function calculates the posterior probabilities (on a log-scale) for
#' each site in an \\eqn{N \\times N} lattice,
#' given:
#' \\enumerate{
#' \\item The current component assignment matrix \\code{z}, indicating
#' which component each site belongs to.
#'   \\item The observed interaction counts \\code{y}.
#'   \\item The neighbor structure encoded by \\code{sum_neighbours}.
#' \\item Model parameters drawn from MCMC chains (\\code{chains},
#' \\code{chain_gamma}, \\code{size_chain}).
#'   \\item The specified distribution (\\code{dist}).
#' }
#'
#' Each component can follow a Poisson, NB, ZIP, or ZINB distribution. For
#' ZIP and ZINB, zero-inflation is applied
#' only to the first component. The negative binomial distributions also
#' incorporate the \\code{size_value} parameter,
#' drawn from \\code{size_chain}.
#'
#' The \\code{pred_combined} function is called to obtain linear predictors
#' \\eqn{\\lambda} for each component.
#' Probabilities are computed for each observation under the chosen
#' distribution and adjusted by the Potts model
#' neighbor effect using \\eqn{\\exp(\\gamma \\times \\text{sum\\_neighbours})}.
#'
#' Finally, the probabilities are logged and returned as an \\eqn{N \\times
#' N} matrix of log-posteriors.
#'
#' @return
#' A numeric \\eqn{N \\times N} matrix of log-posterior values for each site
#' under the given model configuration
#' at the specified iteration.
#'
#' @examples
#' N <- 3
#' z <- matrix(c(1, 1, 2, 3, 1, 3, 2, 3, 1), nrow = N)
#' y <- matrix(rpois(N * N, 3), N, N)
#' x_vars <- list(
#'   list(matrix(runif(N * N, 1, 10), nrow = N)),
#'   list(matrix(runif(N * N, 1, 10), nrow = N)),
#'   list(matrix(runif(N * N, 1, 10), nrow = N)),
#'   list(matrix(runif(N * N, 1, 10), nrow = N))
#' )
#' sum_neighbours <- Neighbours_combined(z, N)
#' chains <- list(matrix(c(1, 0, 0, 0, 0), nrow = 1),
#'                matrix(c(2, 0, 0, 0, 0), nrow = 1),
#'                matrix(c(3, 0, 0, 0, 0), nrow = 1))
#' chain_gamma <- 0.5
#' size_chain <- matrix(c(3, 8, 20), nrow = 3, ncol = 1)
#' pz_vals <- pz_123(z, sum_neighbours, y, pred_combined, chains, chain_gamma,
#' x_vars, theta = 0, size_chain = size_chain, N = N, iter = 0, dist =
#' 'Poisson')
#' head(pz_vals)
#'
#' @noRd
pz_123 <- function(z, sum_neighbours, y, pred_combined, chains, chain_gamma,
    x_vars, theta, size_chain, N, iter, dist) {
    .Call(`_HiCPotts_pz_123`, z, sum_neighbours, y, pred_combined, chains,
        chain_gamma, x_vars, theta, size_chain, N, iter, dist)
}

